Add Spanish Language
FireDiscordBot/bot pull request #24
Opened 2020-09-05 17:50 UTC by Bedlessly

For those spanish people who need a spanish version

2020-09-05 17:51 UTC, GamingGeek requested changes

2020-09-05 17:51 UTC, GamingGeek commented on src/languages/es_ES.ts
> +    super("en-US", {
This need to be changed!

2020-09-05 17:51 UTC, Bedlessly commented on src/languages/es_ES.ts
> +    super("en-US", {
oopsie!

2020-09-05 17:53 UTC, GamingGeek requested changes

2020-09-05 17:53 UTC, GamingGeek commented on src/languages/es_ES.ts
> +          `${key} aún no se ha localizado para en-US.`,
oops forgot to mention this too

2020-09-05 17:53 UTC, Bedlessly commented on src/languages/es_ES.ts
> +          `${key} aún no se ha localizado para en-US.`,
oh shit

2020-09-05 17:56 UTC, merged

2020-09-11 15:26 UTC, GamingGeek commented
If you can, please update this regularly.

2020-09-11 17:35 UTC, Bedlessly commented
oh uhm, ok but cant 100% gauntee i can