Some refactoring and better typescript usage
FireDiscordBot/bot pull request #26
Opened 2020-09-29 19:26 UTC by brunohpaiva

### Code changes

* Better typing:
  * `src/rest/router.ts`
  * discord.js extensions
  * `Command` class
  * `CommandHandler` class
  * `lib/util/converters.ts`
* Simplified route manager and refactored all routes.
* Now fetching discord-akairo admin users id from `ADMINS` env variable.
* Added a `POSTGRES_USER` env variable and fallback to `"postgres"`.
* Moved discord-akairo type casters to separated files.
* Removed useless `SET uid=$2` statement in `updateBlacklist` method from `ClientUtils` class.
* Now using enums for Websocket event types and states.
* Refactored all commands.
* Prettier formatting.

### Misc

* Moved some dependencies to the `devDependecies` property in `package.json`.
* Added `typescript` and `ts-node` dependencies to always use the correct version across other contributors.
* Added `prettier` dependency & config file and also added a npm script `format`. The config file is `.prettierrc`.

2020-09-29 19:40 UTC, brunohpaiva commented
Sk1er's guild module needs testing

2020-09-30 21:03 UTC, GamingGeek requested changes

2020-10-02 19:59 UTC, brunohpaiva commented on lib/providers/postgres.ts
> +    4;
LMAO MY KEYBOARD

2020-10-04 05:28 UTC, brunohpaiva commented
Added `POSTGRES_DB` and `OWNER` env variables, you will need to set them on your env files

2020-10-04 19:44 UTC, GamingGeek commented
There's a few changes that need to be made but I'll just merge and fix them myself since there's not many left.

Thanks :)

2020-10-04 19:45 UTC, merged